FROM ubuntu:focal AS tessdata

RUN apt-get update && apt-get install -y locales zip && rm -rf /var/lib/apt/lists/* \
    && localedef -i en_US -c -f UTF-8 -A /usr/share/locale/locale.alias en_US.UTF-8
ENV LANG en_US.utf8

WORKDIR /app
ADD https://github.com/tesseract-ocr/tessdata/archive/refs/heads/main.zip .

RUN unzip main.zip && rm main.zip && \
    mkdir -p tessdata && mv tessdata-main/*.traineddata tessdata/ && rm -rf tessdata-main/



FROM maven:3.8.3-openjdk-17 AS build
COPY . .
COPY --from=tessdata /app/tessdata /src/main/resources/tessdata
RUN mvn clean package -DskipTests



FROM openjdk:17.0.2-jdk-slim

# Install the necessary dependencies for Tesseract
RUN apt-get update && apt-get install -y \
    tesseract-ocr \
    && rm -rf /var/lib/apt/lists/*

COPY --from=build /target/highlight-server-spring-0.0.1-SNAPSHOT.jar highlightserverspring.jar

RUN mkdir -p /usr/share/tesseract-ocr/4.00/tessdata
COPY --from=build /target/classes/tessdata /usr/share/tesseract-ocr/4.00/tessdata

EXPOSE 8080
ENTRYPOINT ["java","-jar","highlightserverspring.jar"]
